#!/usr/bin/env python3
"""
SWARM Quick Setup Script
Helps configure the bot for first-time use
"""

import os
import sys
from pathlib import Path

def main():
    print("🎯 SWARM Intelligence - Quick Setup")
    print("=" * 50)
    
    # Check if .env exists
    env_file = Path('.env')
    if env_file.exists():
        print("✅ .env file already exists")
        overwrite = input("Do you want to reconfigure? (y/n): ")
        if overwrite.lower() != 'y':
            print("Setup cancelled")
            return
    
    # Get Discord bot token
    print("\n📝 Step 1: Discord Bot Token")
    print("Get this from: https://discord.com/developers/applications")
    token = input("Enter your Discord bot token: ").strip()
    
    if not token:
        print("❌ Token required. Exiting.")
        return
    
    # Optional: Database URL (Railway will auto-provide)
    print("\n📝 Step 2: Database (Optional)")
    print("Leave blank if deploying to Railway (auto-configured)")
    db_url = input("PostgreSQL URL (or press Enter to skip): ").strip()
    
    if not db_url:
        db_url = "sqlite:///swarm.db"  # Default for local dev
        print(f"Using SQLite for local development: {db_url}")
    
    # Create .env file
    env_content = f"""# SWARM Intelligence Discord Bot
# Auto-generated by setup.py

DISCORD_BOT_TOKEN={token}
DATABASE_URL={db_url}

# Channel IDs - Fill these in after creating Discord channels
CHANNEL_CRITICAL_SETUPS=
CHANNEL_ACTIVE_SETUPS=
CHANNEL_WATCHLIST=
CHANNEL_SEC_FILINGS=
CHANNEL_MOMENTUM_SCANNER=
CHANNEL_TECHNICAL_SETUPS=
CHANNEL_NEWS_FEED=
CHANNEL_FINANCIAL_HEALTH=
CHANNEL_TOP_GAINERS=
CHANNEL_TOP_LOSERS=
CHANNEL_COMMUNITY_WATCH=
CHANNEL_DAILY_CONTEXT=

# Role IDs - Fill these in after creating Discord roles
ROLE_PRO=
ROLE_FREE=
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    
    # Check dependencies
    print("\n📦 Checking dependencies...")
    try:
        import discord
        print("✅ discord.py installed")
    except ImportError:
        print("❌ discord.py not installed")
        print("Run: pip install -r requirements.txt")
        return
    
    print("\n🎯 Next Steps:")
    print("1. Create Discord channels and roles")
    print("2. Get channel IDs (Right-click → Copy ID)")
    print("3. Update .env file with channel/role IDs")
    print("4. Run: python bot.py")
    print("\nOr deploy to Railway.app - see README.md")
    
    print("\n✅ Setup complete!")

if __name__ == "__main__":
    main()
